enum TokenType {
    ID,
    INTNUM,
    FLOATNUM,
    EQ = "==",
    GT = ">",
    LT = "<",
    NOTEQ = "<>",
    GEQ = ">=",
    LEQ = "<=",
    RETURNTYPE = "=>",
    PLUS = "+",
    MINUS = "-",
    MULT = "*",
    DIV = "/",
    EQUAL = "=",
    SEMI = ";",
    COMMA = ",",
    SCOPEOP = "::",
    OR = "or",
    AND = "and",
    NOT = "not",
    OPENPAR = "(",
    CLOSEPAR = ")",
    OPENSQBR = "[",
    CLOSESQBR = "]",
    INTEGER = "integer",
    FLOAT = "float",
    VOID = "void",
    CLASS = "class",
    SELF = "self",
    ISA = "isa",
    WHILE = "while",
    IF = "if",
    THEN = "then",
    ELSE = "else",
    READ = "read",
    WRITE = "write",
    RETURN = "return",
    LOCALVAR = "localvar",
    CONSTRUCTOR = "constructor",
    ATTRIBUTE = "attribute",
    FUNCTION = "function",
    PUBLIC = "public",
    PRIVATE = "private",
}

export default TokenType;
